### ISSUE TITLE
Issue with pjit during training

### ISSUE THREAD

**Issue by 4rtemi5** [borisdayma/clip-jax#4]
I'm trying to use the following command to train with the unchanged code on a v3-8 TPU VM: 
`python3 training/train_clip.py --output_dir outputs --config_name training/configs/clip-vit-large-patch16 --tokenizer_name openai/clip-vit-base-patch16`   

I get the following exception:
```
At:
  /home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/_src/sharding.py(162): _check_mesh_resource_axis
  /home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/_src/sharding.py(297): _preprocess
  /home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/interpreters/pxla.py(3716): _create_mesh_pspec_sharding
  /home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py(461): _create_mesh_pspec_sharding_from_parsed_pspec
  /home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py(476): _create_sharding_for_array
  /home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py(358): <lambda>
  /home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/_src/tree_util.py(207): <genexpr>

Traceback (most recent call last):
  File "training/train_clip.py", line 1570, in <module>
    main()
  File "training/train_clip.py", line 941, in main
    state = pjit(
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py", line 135, in cache_miss
    outs, out_flat, out_tree = _python_pjit_helper(infer_params, *args, **kwargs)
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py", line 109, in _python_pjit_helper
    args_flat, _, params, _, out_tree, _ = infer_params(*args, **kwargs)
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py", line 357, in infer_params
    out_shardings = tree_map(
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/_src/tree_util.py", line 207, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/_src/tree_util.py", line 207, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py", line 358, in <lambda>
    lambda x: _create_sharding_for_array(pjit_mesh, x), out_axis_resources)
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py", line 476, in _create_sharding_for_array
    return _create_mesh_pspec_sharding_from_parsed_pspec(mesh, x)
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/experimental/pjit.py", line 461, in _create_mesh_pspec_sharding_from_parsed_pspec
    return pxla._create_mesh_pspec_sharding(mesh, x.user_spec, x)
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 3716, in _create_mesh_pspec_sharding
    return sharding_internal.NamedSharding(mesh, pspec, parsed_pspec)
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/_src/sharding.py", line 297, in _preprocess
    _check_mesh_resource_axis(self.mesh, self._parsed_pspec)
  File "/home/raphaelp/clip-jax/venv/lib/python3.8/site-packages/jax/_src/sharding.py", line 162, in _check_mesh_resource_axis
    raise ValueError(f"Resource axis: {e.args[0]} of {parsed_pspec.user_spec} is "
ValueError: Resource axis: model of PartitionSpec('model', None) is undefined.
```
My pip freeze looks as follows:
```
absl-py==1.3.0
albumentations==1.3.0
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
attrs==22.2.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
braceexpand==0.1.7
cached-property==1.5.2
cachetools==5.2.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
chex==0.1.5
click==8.1.3
-e git+https://github.com/borisdayma/clip-jax.git@bc9269057b11ee38231b4f0908732760442acbf6#egg=clip_jax
comm==0.1.2
commonmark==0.9.1
contourpy==1.0.6
cycler==0.11.0
dataclasses==0.6
debugpy==1.6.4
decorator==5.1.1
defusedxml==0.7.1
dm-tree==0.1.8
docker-pycreds==0.4.0
einops==0.6.0
entrypoints==0.4
etils==0.9.0
exceptiongroup==1.1.0
executing==1.2.0
ExifRead-nocycle==3.0.1
fastjsonschema==2.16.2
filelock==3.8.2
fire==0.4.0
flatbuffers==22.12.6
flax==0.6.3
fonttools==4.38.0
fqdn==1.5.1
fsspec==2022.11.0
gast==0.4.0
gitdb==4.0.10
GitPython==3.1.29
google-auth==2.15.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.51.1
h5py==3.7.0
huggingface-hub==0.11.1
idna==3.4
imageio==2.23.0
img2dataset==1.40.0
importlib-metadata==5.2.0
importlib-resources==5.10.1
iniconfig==1.1.1
ipykernel==6.20.0
ipython==8.7.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jax==0.4.1
jaxlib==0.4.1
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.10
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.5.0
jupyter_client==7.4.8
jupyter_core==5.1.1
jupyter_server==2.0.5
jupyter_server_terminals==0.4.3
jupyterlab==3.5.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
jupyterlab_server==2.17.0
keras==2.11.0
kiwisolver==1.4.4
libclang==14.0.6
libtpu-nightly==0.1.dev20221212
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mistune==2.0.4
msgpack==1.0.4
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.7
nbformat==5.7.1
nest-asyncio==1.5.6
networkx==2.8.8
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.1
oauthlib==3.2.2
opencv-python==4.6.0.66
opencv-python-headless==4.6.0.66
opt-einsum==3.3.0
optax==0.1.4
orbax==0.0.23
packaging==22.0
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.3.0
pkg_resources==0.0.0
pkgutil_resolve_name==1.3.10
platformdirs==2.6.0
pluggy==1.0.0
prometheus-client==0.15.0
promise==2.3
prompt-toolkit==3.0.36
protobuf==3.19.6
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==7.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.19.2
pytest==7.2.0
python-dateutil==2.8.2
python-json-logger==2.0.4
pytz==2022.7
PyWavelets==1.4.1
PyYAML==6.0
pyzmq==24.0.1
qudida==0.0.4
regex==2022.10.31
requests==2.28.1
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==12.6.0
rsa==4.9
scikit-image==0.19.3
scikit-learn==1.2.0
scipy==1.9.3
Send2Trash==1.8.0
sentry-sdk==1.12.1
setproctitle==1.3.2
shortuuid==1.0.11
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
tensorboard==2.11.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-cpu==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io==0.29.0
tensorflow-io-gcs-filesystem==0.29.0
tensorstore==0.1.28
termcolor==2.1.1
terminado==0.17.1
threadpoolctl==3.1.0
tifffile==2022.10.10
tinycss2==1.2.1
tokenizers==0.13.2
tomli==2.0.1
toolz==0.12.0
tornado==6.2
tqdm==4.64.1
traitlets==5.8.0
transformers==4.25.1
typing_extensions==4.4.0
uri-template==1.2.0
urllib3==1.26.13
wandb==0.12.21
wcwidth==0.2.5
webcolors==1.12
webdataset==0.2.31
webencodings==0.5.1
websocket-client==1.4.2
Werkzeug==2.2.2
widgetsnbextension==4.0.5
wrapt==1.14.1
zipp==3.11.0
```

**Comment by borisdayma** [comment]
Can you try latest jax 0.3.*
I haven't checked since 0.4 but may just need to set the JAX array config flag to false until I migrate whatever is necessary.

**Comment by 4rtemi5** [comment]
Hi Boris! Thanks for the quick response!

Using jax==0.3.25 does not seem to fix it. I got the same exception again.  
Also tried to set `jax.config.update('jax_array', False)` right after importing jax which also did not seem to help.

Any other ideas for things I could try?

**Comment by borisdayma** [comment]
That is strange. You have a dataset?
Do you pass "__do_train" also?
One of the spec from the state may have a wrong default.

**Comment by borisdayma** [comment]
A typical command for me would be:
```bash
python train_clip.py 
  --assert_TPU_available 
  --output_dir OUTPUT_FOLDER
  --train_folder xxx
  --config_name configs/clip-xxx
  --learning_rate 0.0001 --warmup_steps 2000
  --tokenizer_name xxx --do_train
  --batch_size_per_node xxx --gradient_accumulation 1 
   --gradient_checkpointing --logging_steps 100 --eval_steps 500 --save_steps 2000 --log_model
```

**Comment by 4rtemi5** [comment]
Yeah I created the dataset with your script from the repo which worked fine.
I was running the exact command I provided above without `--do_train` (silly me) but I get the same error with your command so that should not have been the main issue?  
I keep getting the same exception mentioning `ValueError: Resource axis: model of PartitionSpec('model', None) is undefined.` so I would guess it could be a wrong default.

**Comment by borisdayma** [comment]
Oh I think I found it.
In the training script replace all "dp" with "data" and all "mp" with "model".

The issue is in the partitioning file that I added later I call the model partition "model" while I call it "mp" (as "model parallel") in the training script.

**Comment by 4rtemi5** [comment]
That did it! It's running now! Thanks a lot!

**Comment by borisdayma** [comment]
Nice, let me know how it goes. I'll be working on improving it in the coming weeks.
